- project:
    templates:
      - check-requirements
      - integrated-gate-py3
      - openstack-cover-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py38
        - openstack-tox-py39
        - openstack-tox-py310
        - tempest-full-py3:
            # Define list of irrelevant files to use everywhere else
            irrelevant-files: &tempest-irrelevant-files
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tempest/hacking/.*$
              - ^tempest/tests/.*$
              - ^tools/.*$
              - ^.coveragerc$
              - ^.gitignore$
              - ^.gitreview$
              - ^.mailmap$
        - tempest-extra-tests:
            irrelevant-files: *tempest-irrelevant-files
        - glance-multistore-cinder-import:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        # NOTE(gmann): We will be testing the latest and oldest
        # supported stable branch in Tempest master gate with assuming
        # if things are working in latest and oldest it will work in between
        # stable branches also. If anything is breaking we will be catching
        # those in respective stable branch gate.
        - tempest-full-2023-1:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-yoga:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-multinode-full-py3:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-tox-plugin-sanity-check:
            irrelevant-files: &tempest-irrelevant-files-2
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tempest/hacking/.*$
              - ^tempest/tests/.*$
              - ^.coveragerc$
              - ^.gitignore$
              - ^.gitreview$
              - ^.mailmap$
              - ^tools/check_logs.py
              - ^tools/format.sh
              - ^tools/skip_tracker.py
              - ^tools/tempest-integrated-gate-compute-exclude-list.txt
              - ^tools/tempest-integrated-gate-networking-exclude-list.txt
              - ^tools/tempest-integrated-gate-object-storage-exclude-list.txt
              - ^tools/tempest-integrated-gate-placement-exclude-list.txt
              - ^tools/tempest-integrated-gate-storage-blacklist.txt
              - ^tools/tempest-integrated-gate-storage-exclude-list.txt
              - ^tools/tempest-extra-tests-list.txt
              - ^tools/verify-ipv6-only-deployments.sh
              - ^tools/with_venv.sh
              # tools/ is not here since this relies on a script in tools/.
        - tempest-ipv6-only:
            irrelevant-files: &tempest-irrelevant-files-3
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tempest/hacking/.*$
              - ^tempest/tests/.*$
              - ^tools/check_logs.py
              - ^tools/format.sh
              - ^tools/generate-tempest-plugins-list.py
              - ^tools/generate-tempest-plugins-list.sh
              - ^tools/skip_tracker.py
              - ^tools/tempest-integrated-gate-compute-exclude-list.txt
              - ^tools/tempest-integrated-gate-networking-exclude-list.txt
              - ^tools/tempest-integrated-gate-object-storage-exclude-list.txt
              - ^tools/tempest-integrated-gate-placement-exclude-list.txt
              - ^tools/tempest-integrated-gate-storage-blacklist.txt
              - ^tools/tempest-integrated-gate-storage-exclude-list.txt
              - ^tools/tempest-extra-tests-list.txt
              - ^tools/tempest-plugin-sanity.sh
              - ^tools/with_venv.sh
              - ^.coveragerc$
              - ^.gitignore$
              - ^.gitreview$
              - ^.mailmap$
        - tempest-slow-py3:
            irrelevant-files: *tempest-irrelevant-files
        - nova-live-migration:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-enforce-scope-new-defaults:
            irrelevant-files: *tempest-irrelevant-files
        - devstack-plugin-ceph-tempest-py3:
            # TODO(kopecmartin): make it voting once the below bug is fixed
            # https://bugs.launchpad.net/devstack-plugin-ceph/+bug/1975648
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - neutron-ovs-grenade-multinode:
            irrelevant-files: *tempest-irrelevant-files
        - grenade:
            irrelevant-files: *tempest-irrelevant-files
        - neutron-ovs-tempest-dvr:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - interop-tempest-consistency:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-test-account-py3:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - openstack-tox-bashate:
            irrelevant-files: *tempest-irrelevant-files-2
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py38
        - openstack-tox-py39
        - openstack-tox-py310
        - tempest-slow-py3:
            irrelevant-files: *tempest-irrelevant-files
        - neutron-ovs-grenade-multinode:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-py3:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-extra-tests:
            irrelevant-files: *tempest-irrelevant-files
        - grenade:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-ipv6-only:
            irrelevant-files: *tempest-irrelevant-files-3
        - tempest-multinode-full-py3:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-enforce-scope-new-defaults:
            irrelevant-files: *tempest-irrelevant-files
        #- devstack-plugin-ceph-tempest-py3:
        #    irrelevant-files: *tempest-irrelevant-files
        - nova-live-migration:
            irrelevant-files: *tempest-irrelevant-files
    experimental:
      jobs:
        - nova-multi-cell
        - nova-ceph-multistore:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-with-latest-microversion
        - tempest-stestr-master
        - tempest-cinder-v2-api:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-all:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-slow-parallel
        - tempest-full-parallel
        - tempest-full-zed-extra-tests
        - tempest-full-yoga-extra-tests
        - tempest-full-enforce-scope-new-defaults-zed
        - neutron-ovs-tempest-dvr-ha-multinode-full:
            irrelevant-files: *tempest-irrelevant-files
        - nova-tempest-v2-api:
            irrelevant-files: *tempest-irrelevant-files
        - cinder-tempest-lvm-multibackend:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-pg-full:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-py3-ipv6:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-centos-9-stream:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-centos9-stream-fips:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-test-account-no-admin-py3:
            irrelevant-files: *tempest-irrelevant-files
    periodic-stable:
      jobs:
        - tempest-full-2023-1
        - tempest-full-zed
        - tempest-full-yoga
        - tempest-slow-2023-1
        - tempest-slow-zed
        - tempest-slow-yoga
        - tempest-full-2023-1-extra-tests
        - tempest-full-zed-extra-tests
        - tempest-full-yoga-extra-tests
    periodic:
      jobs:
        - tempest-all
        - tempest-slow-parallel
        - tempest-full-parallel
        - tempest-full-oslo-master
        - tempest-stestr-master
        - tempest-full-py3-ipv6
        - tempest-centos9-stream-fips
        - tempest-full-centos-9-stream
        - tempest-full-test-account-no-admin-py3
        - tempest-full-enforce-scope-new-defaults-zed
