- project:
    templates:
      - check-requirements
      - integrated-gate-py3
      - openstack-cover-jobs
      - openstack-python3-xena-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - tempest-full-parallel:
            # Define list of irrelevant files to use everywhere else
            irrelevant-files: &tempest-irrelevant-files
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tempest/hacking/.*$
              - ^tempest/tests/.*$
              - ^tools/.*$
              - ^.coveragerc$
              - ^.gitignore$
              - ^.gitreview$
              - ^.mailmap$
        - tempest-full-py3:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-py3-ipv6:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - glance-multistore-cinder-import:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-wallaby-py3:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-victoria-py3:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-ussuri-py3:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-train-py3:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-multinode-full-py3:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-tox-plugin-sanity-check:
            irrelevant-files: &tempest-irrelevant-files-2
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tempest/hacking/.*$
              - ^tempest/tests/.*$
              - ^.coveragerc$
              - ^.gitignore$
              - ^.gitreview$
              - ^.mailmap$
              - ^tools/check_logs.py
              - ^tools/format.sh
              - ^tools/skip_tracker.py
              - ^tools/tempest-integrated-gate-compute-exclude-list.txt
              - ^tools/tempest-integrated-gate-networking-exclude-list.txt
              - ^tools/tempest-integrated-gate-object-storage-exclude-list.txt
              - ^tools/tempest-integrated-gate-placement-exclude-list.txt
              - ^tools/tempest-integrated-gate-storage-blacklist.txt
              - ^tools/tempest-integrated-gate-storage-exclude-list.txt
              - ^tools/verify-ipv6-only-deployments.sh
              - ^tools/with_venv.sh
              # tools/ is not here since this relies on a script in tools/.
        - tempest-ipv6-only:
            irrelevant-files: &tempest-irrelevant-files-3
              - ^.*\.rst$
              - ^doc/.*$
              - ^etc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tempest/hacking/.*$
              - ^tempest/tests/.*$
              - ^tools/check_logs.py
              - ^tools/format.sh
              - ^tools/generate-tempest-plugins-list.py
              - ^tools/generate-tempest-plugins-list.sh
              - ^tools/skip_tracker.py
              - ^tools/tempest-integrated-gate-compute-exclude-list.txt
              - ^tools/tempest-integrated-gate-networking-exclude-list.txt
              - ^tools/tempest-integrated-gate-object-storage-exclude-list.txt
              - ^tools/tempest-integrated-gate-placement-exclude-list.txt
              - ^tools/tempest-integrated-gate-storage-blacklist.txt
              - ^tools/tempest-integrated-gate-storage-exclude-list.txt
              - ^tools/tempest-plugin-sanity.sh
              - ^tools/with_venv.sh
              - ^.coveragerc$
              - ^.gitignore$
              - ^.gitreview$
              - ^.mailmap$
        - tempest-slow-py3:
            irrelevant-files: *tempest-irrelevant-files
        - nova-live-migration:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - devstack-plugin-ceph-tempest-py3:
            irrelevant-files: *tempest-irrelevant-files
        - neutron-ovs-grenade-multinode:
            irrelevant-files: *tempest-irrelevant-files
        - grenade:
            irrelevant-files: *tempest-irrelevant-files
        - neutron-ovs-tempest-dvr:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - interop-tempest-consistency:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-test-account-py3:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-test-account-no-admin-py3:
            voting: false
            irrelevant-files: *tempest-irrelevant-files
        - openstack-tox-bashate:
            irrelevant-files: *tempest-irrelevant-files-2
    gate:
      jobs:
        - tempest-slow-py3:
            irrelevant-files: *tempest-irrelevant-files
        - neutron-ovs-grenade-multinode:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-py3:
            irrelevant-files: *tempest-irrelevant-files
        - grenade:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-ipv6-only:
            irrelevant-files: *tempest-irrelevant-files-3
        - devstack-plugin-ceph-tempest-py3:
            irrelevant-files: *tempest-irrelevant-files
    experimental:
      jobs:
        - tempest-with-latest-microversion
        - tempest-stestr-master
        - tempest-cinder-v2-api:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-all:
            irrelevant-files: *tempest-irrelevant-files
        - neutron-ovs-tempest-dvr-ha-multinode-full:
            irrelevant-files: *tempest-irrelevant-files
        - nova-tempest-v2-api:
            irrelevant-files: *tempest-irrelevant-files
        - cinder-tempest-lvm-multibackend:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-pg-full:
            irrelevant-files: *tempest-irrelevant-files
        - tempest-full-py3-opensuse15:
            irrelevant-files: *tempest-irrelevant-files
    periodic-stable:
      jobs:
        - tempest-full-wallaby-py3
        - tempest-full-victoria-py3
        - tempest-full-ussuri-py3
        - tempest-full-train-py3
    periodic:
      jobs:
        - tempest-all
        - tempest-full-oslo-master
        - tempest-stestr-master
